# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Animal.destroy_all

animal1 = Animal.create(category: "cat",name: "Leo", gender: "boy", age: "Teenager", size: "M", remote: true,  animal_bio: "🧏 Leo was given to us at the shelter because his owner could no longer take care of him for health reasons.Since he is deaf, he becomes more shy. He likes staying with Ella who came to us as a found animal.Deaf Leo meows loudly if he has to wait too long for company. Since Leo's sensitive stomach is especially sensitive to stress, his new family (preferably with older, responsible children) should have a relaxed atmosphere. ")
animal2 = Animal.create(category: "cat",name: "Schneckerl", gender: "girl", age: "Adult", size: "S", remote: true,  animal_bio: "📢 The nervous, very insecure and sensitive cat diva brings a wide range of characteristics. Only!!! if Schneckerl wants it, she gives completely the dear velvet paw: Trusting, people-oriented and cuddly she ensnares her people. She is happy when people play with her and enjoys the presence of her owners. However, Schneckerl is also very moody, somewhat unpredictable, fearful and sometimes panic-stricken. She is sensitive to noises, so she does not get along with children at all. In addition, she screams at night.")
animal3 = Animal.create(category: "cat",name: "Flokati", gender: "girl", age: "Elder", size: "S", remote: true,  animal_bio: "👵 One thing is 100% certain with Flokati, she is not dependent on anything or anyone. Flokati is a little diva who is neither cuddly nor playful. She is perfectly content with her own company and does not want to be crowded. However, we firmly believe that even a goddess needs soothing cuddles from time to time once she has taken a human into her heart. Flokati requires intensive medical care, which takes some practice.")
animal4 = Animal.create(category: "dog",name: "Apollo", gender: "boy", age: "Adult", size: "XL", remote: false,  animal_bio: "The well-mannered male shows normal breed-typical behavior, and is looking forward to a new home which he will guard dutifully and with great pleasure. He already masters important commands, but there are still difficulties with the leash. Here it still needs some practice and routine. If the pretty Doberman feels underchallenged, he will whine, squeal and yelp. A hernia from the past which has also left its traces visually is responsible for this. Otherwise Apollo shows himself trusting, people-oriented and is happy about extensive cuddles. The journey by car or public transport is no problem for him. The new owners may bring with pleasure already race or dog experience. Consistent safe leadership, as well as a quiet home would be ideal conditions for a relaxed and stress-free life together.")
animal5 = Animal.create(category: "dog",name: "Shadow", gender: "boy", age: "Adult", size: "L", remote: false,  animal_bio:"The handsome male is friendly, but a little reserved with strangers at first. After a short acclimatization he is very cuddly, but also typical for the breed a little peculiar. Shadow likes to be outside a lot, is playful and loves to splash in the water. A house with a garden would be ideal for him and Sharlot. He is largely neutral towards other dogs, depending on sympathy.")
puts "Cute animals"
